# CXF-Client "imperium": WSDL aus dem Adapter-JAR, Timeouts 2 s (in Millisekunden)
quarkus.cxf.client."imperium".wsdl=wsdl/imperium-werft.wsdl
quarkus.cxf.client."imperium".connection-timeout=2000
quarkus.cxf.client."imperium".receive-timeout=2000
